"""Emit the detailed per-config PPAC CSV for the LRA-Text (IMDB) task.

DELIBERATELY SEPARATE from make_ppac_detailed_csv.py, which owns the ListOps
four-corner record. Same model, same rules, different task and a different
output file, so an IMDB run can never overwrite or mix into the ListOps numbers.

Everything is regenerated by EXECUTING the model. The activation tier is derived
from each config's own extracted workload by
multi_array_ppac_v4.auto_tier (rule: smallest ladder step >= max over GEMMs of
M*K + M*N bytes), which reproduces every hand-assigned ListOps tier exactly.
Weight SRAM is sized from the parameter count at one INT8 byte per parameter,
rounded to a 64 KB bank.

Configs are processed only if their workload has been extracted, so this can be
run while the remaining checkpoints are still training.

Usage (cluster, where the workloads live):
    python paper_v2_ppac/make_ppac_imdb_csv.py
Writes ppac_detailed_imdb.csv into the figure-data directories.
"""
import csv
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "chip"))

import multi_array_ppac_v4 as m4          # noqa: E402
import multi_array_ppac_v5 as m5          # noqa: E402

OUT_DIRS = [
    os.path.join(HERE, "figure_data_v1"),
    os.path.expanduser("~/dev/nc-block/paper/mambino-paper/figure_data_v1"),
]

# canonical name -> (workload/config key, arm)
CONFIGS = [
    ("S5-0",      "imdb-S5-0",        "iso"),
    ("Mambino-0", "imdb-Mambino-0",   "iso"),
    ("Mambino-G", "imdb-Mambino-G",   "iso"),
    ("S5-Dense",  "imdb-S5-Dense",    "baseline"),
    ("S5-0-R",      "imdb-S5-0-R",      "reduced"),
    ("Mambino-0-R", "imdb-Mambino-0-R", "reduced"),
    ("Mambino-G-R", "imdb-Mambino-G-R", "reduced"),
]

# 8-seed test@peakval means; filled in as runs land. None = not yet measured, in
# which case accuracy-derived columns are left blank rather than guessed.
ACC = {
    "imdb-S5-0": None, "imdb-Mambino-0": None, "imdb-Mambino-G": None,
    "imdb-S5-Dense": None, "imdb-S5-0-R": None, "imdb-Mambino-0-R": None,
    "imdb-Mambino-G-R": None,
}

HEADER = ["config", "arm", "params", "act_tier_KB", "wsram_KB", "PEs",
          "area_mm2", "pe_area_mm2", "act_sram_mm2", "weight_sram_mm2",
          "latency_ms", "throughput_ips", "energy_uJ", "avg_mW",
          "acc", "acc_per_Mparam", "acc_per_mJ", "acc_per_mm2",
          "IPW_acc_per_W_avg"]


def main():
    rows, missing = [], []
    for name, cfg, arm in CONFIGS:
        wl = os.path.join(HERE, "workloads", f"workload_{cfg}_gemms.yaml")
        if not os.path.exists(wl):
            missing.append(name)
            continue
        acc = ACC.get(cfg)
        m4.ACC[cfg] = acc if acc is not None else 0.0   # model requires a value
        r = m5.atp_optimal(cfg, honest=True)
        par = m4.param_count(cfg)
        area, lat = r["total_area_mm2"], r["lat_serial_ms"]
        energy = r["energy_full_uJ"]
        avg = energy / lat
        d = ["", "", "", ""]
        if acc is not None:
            d = [f"{acc / (par / 1e6):.6f}", f"{1000.0 * acc / energy:.6f}",
                 f"{acc / area:.8f}", f"{acc / (avg / 1000.0):.6f}"]
        rows.append([name, arm, par, m4.TIER_KB[m4.tier_of(cfg)],
                     m4.weight_sram_bytes(cfg) // 1024, r["total_pe"],
                     f"{area:.6f}", f"{r['pe_area_mm2']:.6f}",
                     f"{r['act_sram_area_mm2']:.6f}", f"{r['weight_sram_area_mm2']:.6f}",
                     f"{lat:.6f}", f"{r['throughput_ips']:.4f}",
                     f"{energy:.6f}", f"{avg:.6f}",
                     f"{acc:.4f}" if acc is not None else ""] + d)

    if not rows:
        print("no IMDB workloads extracted yet; nothing to write")
        return 1
    for dd in OUT_DIRS:
        if not os.path.isdir(dd):
            print(f"  SKIP (no such dir) {dd}")
            continue
        p = os.path.join(dd, "ppac_detailed_imdb.csv")
        with open(p, "w", newline="") as f:
            w = csv.writer(f)
            w.writerow(HEADER)
            w.writerows(rows)
        print(f"  wrote {p}  ({len(rows)} rows)")
    if missing:
        print(f"  not yet extracted: {', '.join(missing)}")
    print()
    print(f"{'config':<13}{'arm':<10}{'params':>10}{'tier':>7}{'PEs':>7}"
          f"{'area':>9}{'act SRAM':>10}{'energy':>9}{'avg mW':>9}")
    for r in rows:
        print(f"{r[0]:<13}{r[1]:<10}{int(r[2]):>10,}{r[3]:>7}{r[5]:>7}"
              f"{float(r[6]):>9.2f}{float(r[8]):>10.2f}{float(r[12]):>9.1f}{float(r[13]):>9.1f}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
