"""Full v2 chip PPAC pipeline with array-size ablation.

For each of {8x8, 16x16, 32x32, 64x64} systolic weight-stationary arrays:
  - Runs timeloop-model on each of the 10 unique GEMM shapes (Phase 4)
  - Aggregates per-config: energy, cycles, latency, power, throughput,
    pJ/real-MAC, per-component breakdown (Phase 5)

Then emits:
  per_gemm_ppac.json      -- per (shape, array_size) Timeloop stats
  per_config_ppac.json    -- per (config, array_size) aggregate + metrics
  sweep_summary.csv       -- flat table for plotting Fig 4 / Fig 5

For each config, reports the DESIGNER-OPTIMUM array size on the metrics:
  best energy_per_inference, best acc/mJ, best power, best acc × throughput/W.
"""
from __future__ import annotations

import argparse
import csv
import json
import os
import re
import subprocess
from pathlib import Path
from typing import NamedTuple

import yaml

FREQ_HZ = 1e9   # 1 GHz across all array sizes (paper's chip clock target)
ARRAY_SIZES = [(8, 8), (16, 16), (32, 32), (64, 64)]

# Accuracy per config from master doc §5a (test@peakval, 8-seed mean)
ACC = {"config4": 0.5993, "config5": 0.5917,
       "corner1": 0.6089, "corner2": 0.5991, "corner3p": 0.6138}


class Gemm(NamedTuple):
    M: int; N: int; K: int
    dtype: str
    per_mac_flops: int

    def dtype_scale(self) -> int:
        return self.per_mac_flops // 2  # 1, 2, or 4


def factor_split(dim: int, spatial_max: int) -> tuple[int, int]:
    """Return (spatial_factor, temporal_factor) with product == dim, spatial ≤ max."""
    if dim <= spatial_max:
        return dim, 1
    best = 1
    for f in range(1, spatial_max + 1):
        if dim % f == 0 and f > best:
            best = f
    return best, dim // best


def emit_cfg(gemm: Gemm, cfg_path: Path, array_x: int, array_y: int):
    """Timeloop libconfig .cfg for this GEMM on an (array_x × array_y) WS chip.

    Buffer size scales with array so each array's per-PE footprint stays sensible:
      GlobalBuffer = max(1 MB, 4 × array_footprint)  -- fits all workloads on-chip
    """
    n_pe = array_x * array_y
    # 1 MB minimum; scale up if the largest workload's activation footprint would exceed
    # (max footprint across our workloads is ~600 KB; 1 MB is plenty for 8x8..64x64).
    gb_kb = 1024

    M_sp, M_tp = factor_split(gemm.M, array_y)
    N_sp, N_tp = factor_split(gemm.N, array_x)
    K_tp = gemm.K

    # Timeloop uses CNN dimensions (Q=M, K=N, C=K)
    Q, K_out, C = gemm.M, gemm.N, gemm.K
    Q_sp, Q_tp = M_sp, M_tp
    K_out_sp, K_out_tp = N_sp, N_tp

    cfg = f"""# Auto-generated by run_all_configs_ppac.py
# GEMM: M={gemm.M} N={gemm.N} K={gemm.K} dtype={gemm.dtype}
# Chip: {array_x}x{array_y} WS array ({n_pe} PEs), 22nm INT8, {gb_kb} KB GlobalBuffer
arch :
{{
  arithmetic : {{ instances = {n_pe}; word-bits = 8; meshX = {array_x}; }};
  storage = (
    {{ name = "PsumSpad"; entries = 1; instances = {n_pe}; meshX = {array_x}; word-bits = 32; }},
    {{ name = "WeightSpad"; entries = 1; instances = {n_pe}; meshX = {array_x}; word-bits = 8; }},
    {{ name = "GlobalBuffer"; sizeKB = {gb_kb}; instances = 1; word-bits = 8; }} );
}};
problem : {{ R = 1; S = 1; P = 1; Q = {Q}; C = {C}; K = {K_out}; N = 1;
            Wstride = 1; Hstride = 1; Wdilation = 1; Hdilation = 1; }};
mapping = (
    {{ target = 0; type = "datatype"; keep = [ "Weights" ]; bypass = [ "Inputs", "Outputs" ]; }},
    {{ target = 1; type = "datatype"; keep = [ "Outputs" ]; bypass = [ "Weights", "Inputs" ]; }},
    {{ target = 2; type = "datatype"; keep = [ "Weights", "Inputs", "Outputs" ]; bypass = [ ]; }},
    {{ target = 2; type = "temporal"; factors = "R1 S1 P1 Q{Q_tp} C{K_tp} K{K_out_tp} N1"; permutation = "CQKPRSN"; }},
    {{ target = 2; type = "spatial"; factors = "R1 S1 P1 Q{Q_sp} C1 K{K_out_sp} N1"; permutation = "QKRSPCN"; split = 1; }},
    {{ target = 0; type = "temporal"; factors = "R1 S1 P1 Q1 C1 K1 N1"; permutation = "CQKRSPN"; }}
);
"""
    cfg_path.write_text(cfg)


class Stats(NamedTuple):
    cycles: int; util_pct: float; energy_uJ: float; pj_per_mac: float
    per_component: dict[str, float]


def parse_stats(txt: str) -> Stats:
    cycles = int(re.search(r"Cycles: (\d+)", txt).group(1))
    util = float(re.search(r"Utilization: ([\d.]+)%", txt).group(1))
    e = float(re.search(r"Energy: ([\d.]+) uJ", txt).group(1))
    per = {}
    m = re.search(r"pJ/Compute\s*\n((?:\s*\w+\s*=\s*[\d.]+\s*\n)+)", txt)
    if m:
        for line in m.group(1).strip().split("\n"):
            mm = re.match(r"\s*(\S+)\s*=\s*([\d.]+)", line)
            if mm: per[mm.group(1)] = float(mm.group(2))
    total = per.pop("Total", 0.0)
    return Stats(cycles=cycles, util_pct=util, energy_uJ=e, pj_per_mac=total, per_component=per)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--workloads_dir",
                    default=os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "workloads")))
    ap.add_argument("--chip_dir",
                    default=os.path.dirname(os.path.abspath(__file__)))
    ap.add_argument("--timeloop_bin",
                    default=os.path.expanduser("~/local/src/timeloop/build/timeloop-model"))
    args = ap.parse_args()

    workloads = Path(args.workloads_dir)
    chip = Path(args.chip_dir)

    # 1. Load all 5 configs' workloads
    configs = ["config4", "config5", "corner1", "corner2", "corner3p"]
    unique_gemms: dict[tuple, Gemm] = {}
    per_config_instances: dict[str, list[dict]] = {c: [] for c in configs}
    for cfg in configs:
        d = yaml.safe_load(open(workloads / f"workload_{cfg}_gemms.yaml"))
        for g in d['gemms']:
            key = (g['M'], g['N'], g['K'], g['dtype'])
            unique_gemms[key] = Gemm(M=g['M'], N=g['N'], K=g['K'], dtype=g['dtype'],
                                     per_mac_flops=g['per_mac_flops'])
            per_config_instances[cfg].append(
                dict(shape=key, repeat=g['repeat'], real_macs=g['total_real_macs']))
    print(f"[sweep] {len(unique_gemms)} unique GEMM shapes × {len(ARRAY_SIZES)} array sizes = "
          f"{len(unique_gemms) * len(ARRAY_SIZES)} timeloop-model runs")

    # 2. Sweep — run timeloop-model on every (shape × array_size) pair
    per_gemm_result: dict[tuple, dict] = {}   # (shape_id, array_x, array_y) -> stats

    for ax, ay in ARRAY_SIZES:
        work = chip / f"per_gemm_stats_{ax}x{ay}"
        work.mkdir(parents=True, exist_ok=True)
        print(f"\n[sweep] === Array {ax}x{ay} ({ax*ay} PEs) ===")
        for i, (key, gemm) in enumerate(sorted(unique_gemms.items()), 1):
            shape_id = f"M{gemm.M}_N{gemm.N}_K{gemm.K}_{gemm.dtype}"
            cfg_path = work / f"gemm_{shape_id}.cfg"
            stats_path = work / f"gemm_{shape_id}.stats.txt"
            emit_cfg(gemm, cfg_path, ax, ay)
            proc = subprocess.run(
                [args.timeloop_bin, str(cfg_path.resolve())],
                capture_output=True, text=True, cwd=str(work), timeout=120)
            default_stats = work / "timeloop-model.stats.txt"
            if not default_stats.exists() or proc.returncode != 0:
                print(f"  [{i:2d}/{len(unique_gemms)}] {shape_id}  FAILED  "
                      f"({(proc.stderr or 'no-stats')[-160:].strip()})")
                per_gemm_result[(shape_id, ax, ay)] = dict(status="fail")
                continue
            default_stats.rename(stats_path)
            for junk in ["timeloop-model.map.txt", "timeloop-model.map+stats.xml"]:
                (work / junk).unlink(missing_ok=True)
            stats = parse_stats(stats_path.read_text())
            per_gemm_result[(shape_id, ax, ay)] = dict(
                status="ok", shape=[gemm.M, gemm.N, gemm.K], dtype=gemm.dtype,
                per_mac_flops=gemm.per_mac_flops,
                cycles=stats.cycles, util_pct=stats.util_pct,
                energy_uJ=stats.energy_uJ, pj_per_mac=stats.pj_per_mac,
                per_component_pJ_per_mac=stats.per_component,
            )
            print(f"  [{i:2d}/{len(unique_gemms)}] {shape_id:<32}  "
                  f"Cyc={stats.cycles:>10,}  Util={stats.util_pct:5.1f}%  "
                  f"E={stats.energy_uJ:8.3f} μJ  pJ/MAC={stats.pj_per_mac:.3f}")

    # Save raw per-GEMM data (with array_size in key)
    serializable = {f"{k[0]}__{k[1]}x{k[2]}": v for k, v in per_gemm_result.items()}
    (chip / "per_gemm_ppac.json").write_text(json.dumps(serializable, indent=2, default=str))

    # 3. Per-config aggregate per array size
    sweep_rows = []
    per_config_full: dict[str, dict] = {}
    for cfg in configs:
        per_config_full[cfg] = {}
        for ax, ay in ARRAY_SIZES:
            total_energy_uJ = 0.0
            total_cycles = 0
            component_uJ = {}
            for inst in per_config_instances[cfg]:
                M, N, K, dt = inst['shape']
                shape_id = f"M{M}_N{N}_K{K}_{dt}"
                r = per_gemm_result.get((shape_id, ax, ay))
                if not r or r.get('status') != 'ok':
                    continue
                gemm = Gemm(M=M, N=N, K=K, dtype=dt, per_mac_flops=r['per_mac_flops'])
                # Scale for dtype: complex×real=2×, complex×complex=4× the "logical" MACs
                e_inst = r['energy_uJ'] * gemm.dtype_scale()
                cyc_inst = r['cycles'] * gemm.dtype_scale()
                total_energy_uJ += e_inst * inst['repeat']
                total_cycles += cyc_inst * inst['repeat']
                for comp, pj in r['per_component_pJ_per_mac'].items():
                    e_comp = pj * (M * N * K) * gemm.dtype_scale() * inst['repeat'] / 1e6
                    component_uJ[comp] = component_uJ.get(comp, 0.0) + e_comp

            latency_s = total_cycles / FREQ_HZ
            energy_j = total_energy_uJ / 1e6
            power_w = energy_j / latency_s if latency_s > 0 else 0
            throughput = 1.0 / latency_s if latency_s > 0 else 0
            total_real_macs = sum(i['real_macs'] for i in per_config_instances[cfg])
            pj_per_real_mac = total_energy_uJ * 1e6 / total_real_macs if total_real_macs else 0
            acc = ACC[cfg]
            row = dict(
                config=cfg, accuracy=acc, array_x=ax, array_y=ay, n_pe=ax*ay,
                energy_mJ=total_energy_uJ / 1000,
                latency_ms=latency_s * 1e3,
                power_mW=power_w * 1e3,
                throughput_ips=throughput,
                total_cycles=total_cycles,
                pj_per_real_mac=pj_per_real_mac,
                acc_per_mJ=acc / (total_energy_uJ / 1000) if total_energy_uJ > 0 else 0,
                acc_x_throughput_per_W=acc * throughput / power_w if power_w > 0 else 0,
                per_component_uJ=component_uJ,
            )
            per_config_full[cfg][f"{ax}x{ay}"] = row
            sweep_rows.append(row)

    (chip / "per_config_ppac.json").write_text(json.dumps(per_config_full, indent=2, default=str))

    # 4. Flat CSV for plotting
    csv_path = chip / "sweep_summary.csv"
    with open(csv_path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow([
            "config", "accuracy", "array_x", "array_y", "n_pe",
            "energy_mJ", "latency_ms", "power_mW", "throughput_ips",
            "total_cycles", "pj_per_real_mac",
            "acc_per_mJ", "acc_x_throughput_per_W",
        ])
        for r in sweep_rows:
            w.writerow([
                r["config"], r["accuracy"], r["array_x"], r["array_y"], r["n_pe"],
                round(r["energy_mJ"], 4), round(r["latency_ms"], 4),
                round(r["power_mW"], 2), round(r["throughput_ips"], 2),
                r["total_cycles"], round(r["pj_per_real_mac"], 3),
                round(r["acc_per_mJ"], 4), round(r["acc_x_throughput_per_W"], 3),
            ])
    print(f"\n[sweep] wrote {csv_path.name}")

    # 5. Report each config's optimum array size on 4 metrics
    print(f"\n{'='*104}")
    print("Designer-optimum array size per config (on each of 4 metrics)")
    print(f"{'='*104}")
    header = f"{'Config':<12}{'Metric':<28}{'Optimum':<12}{'Value':>14}   {'All array sizes'}"
    print(header)
    print("-" * 104)
    metrics = [
        ("min energy_mJ", "energy_mJ", min, "mJ"),
        ("max acc/mJ",    "acc_per_mJ", max, ""),
        ("min power_mW",  "power_mW", min, "mW"),
        ("max acc×tps/W", "acc_x_throughput_per_W", max, ""),
    ]
    for cfg in configs:
        for label, key, fn, unit in metrics:
            sizes = list(per_config_full[cfg].keys())
            values = [per_config_full[cfg][s][key] for s in sizes]
            i = values.index(fn(values))
            opt = sizes[i]
            v = values[i]
            all_vals = "  ".join(f"{s}: {v:.3f}" for s, v in zip(sizes, values))
            print(f"{cfg:<12}{label:<28}{opt:<12}{v:>10.4f} {unit:>3}   {all_vals}")
        print()

    # 6. Full sweep table (all 20 rows)
    print(f"{'='*140}")
    print(f"Full sweep — {len(sweep_rows)} rows (5 configs × {len(ARRAY_SIZES)} array sizes)")
    print(f"{'='*140}")
    print(f"{'Config':<10}{'Array':<10}{'Acc':>8}{'Energy':>12}{'Latency':>12}{'Power':>10}"
          f"{'Throughput':>14}{'acc/mJ':>10}{'acc×TPS/W':>14}")
    print("-" * 140)
    for r in sweep_rows:
        print(f"{r['config']:<10}{r['array_x']}x{r['array_y']:<8}{r['accuracy']:>8.4f}"
              f"{r['energy_mJ']:>9.3f} mJ{r['latency_ms']:>9.3f} ms"
              f"{r['power_mW']:>8.1f} mW{r['throughput_ips']:>11.1f} /s"
              f"{r['acc_per_mJ']:>10.4f}{r['acc_x_throughput_per_W']:>14.3f}")


if __name__ == "__main__":
    main()
